ALTER TABLE leadrecords CHANGE enquiry_date enquiry_date DATETIME DEFAULT NULL;
ALTER TABLE leadrecords Drop enquiry_time;
ALTER TABLE leadrecords MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE leadrecords MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;